#include "core/maps.hpp"

static char data[] =
    "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o                                               o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "o    oooo oooooooooooooooooo    ooo ooooooooooo o o o o o oo"
    "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo"
;

DEFINE_MAP(full, 60, 48, data)
